#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { cac } from 'cac';
import pc from 'picocolors';
import {
  intro,
  outro,
  confirm,
  multiselect,
  isCancel,
  log,
  cancel,
} from '@clack/prompts';

// ─── Types ────────────────────────────────────────────────────────────────────
interface Tool {
  label: string;
  hint: string;
  dest: string;
  filePrefix: string;
  ignoreRules: string[];
  srcDir: string;
}

interface Config {
  tools: Record<string, boolean>;
}

interface PkgJson {
  name: string;
  version: string;
}

// ─── Tool registry ────────────────────────────────────────────────────────────
const TOOLS: Record<string, Tool> = {
  cursor: {
    label: 'Cursor IDE',
    hint: 'Copies .mdc rules → .cursor/rules/ (prefixed qa-ai-rules--)',
    dest: '.cursor/rules',
    filePrefix: 'qa-ai-rules--',
    ignoreRules: ['.cursor/rules/qa-ai-rules--*'],
    srcDir: 'cursor',
  },
  claude: {
    label: 'Claude Code',
    hint: 'Copies rules → .claude/rules/qa-ai-rules/',
    dest: '.claude/rules/qa-ai-rules',
    filePrefix: '',
    ignoreRules: ['.claude/rules/qa-ai-rules/'],
    srcDir: 'claude',
  },
};

// ─── Paths ────────────────────────────────────────────────────────────────────
const PROJECT_ROOT = process.cwd();
const PKG_ROOT = path.resolve(__dirname, '..');
const CONFIG_PATH = path.join(PROJECT_ROOT, 'qa-ai-rules.config.json');
const GITIGNORE = path.join(PROJECT_ROOT, '.gitignore');

const pkg = JSON.parse(
  fs.readFileSync(path.join(PKG_ROOT, 'package.json'), 'utf8'),
) as PkgJson;

// ─── Config helpers ───────────────────────────────────────────────────────────
function loadConfig(): Config | null {
  if (!fs.existsSync(CONFIG_PATH)) {
    return null;
  }

  try {
    return JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8')) as Config;
  } catch {
    return null;
  }
}

function writeConfig(tools: Record<string, boolean>): void {
  fs.writeFileSync(CONFIG_PATH, JSON.stringify({ tools }, null, 2) + '\n');
  log.success('qa-ai-rules.config.json written');
}

// ─── .gitignore helpers ───────────────────────────────────────────────────────
function getMissingIgnoreRules(enabledTools: Record<string, boolean>): {
  missing: string[];
  stale: string[];
} {
  const lines = fs.existsSync(GITIGNORE)
    ? fs.readFileSync(GITIGNORE, 'utf8').split('\n')
    : [];
  const missing: string[] = [];
  const stale: string[] = [];

  for (const [key, tool] of Object.entries(TOOLS)) {
    for (const rule of tool.ignoreRules) {
      const present = lines.some((l: string) => l.trim() === rule);

      if (enabledTools[key] && !present) {
        missing.push(rule);
      }

      if (!enabledTools[key] && present) {
        stale.push(rule);
      }
    }
  }

  return { missing, stale };
}

async function handleGitignore(
  enabledTools: Record<string, boolean>,
): Promise<void> {
  const { missing, stale } = getMissingIgnoreRules(enabledTools);

  if (missing.length === 0) {
    log.success('All required .gitignore rules already present');
  } else {
    log.warn(
      `Missing ${missing.length} ignore rule(s):\n${missing.map((r) => `  ${pc.dim(r)}`).join('\n')}`,
    );

    const add = await confirm({ message: 'Add missing rules to .gitignore?' });

    if (isCancel(add)) {
      cancel('Operation cancelled');
      process.exit(0);
    }

    if (add) {
      const comment =
        '# Generated by @metricinsights/qa-ai-rules — do not edit these files directly';
      const block = `\n${comment}\n${missing.join('\n')}`;
      const existing = fs.existsSync(GITIGNORE)
        ? fs.readFileSync(GITIGNORE, 'utf8')
        : '';
      const sep = existing.length && !existing.endsWith('\n') ? '\n' : '';

      fs.writeFileSync(GITIGNORE, existing + sep + block + '\n');
      log.success('.gitignore updated');
    } else {
      log.warn('Skipped — generated files will NOT be gitignored');
    }
  }

  if (stale.length > 0) {
    log.warn(
      `${stale.length} stale rule(s) for disabled tools:\n${stale.map((r) => `  ${pc.dim(r)}`).join('\n')}`,
    );
    log.info('You may want to remove them manually from .gitignore');
  }
}

// ─── File installation ────────────────────────────────────────────────────────
function installFiles(enabledTools: Record<string, boolean>): void {
  for (const [key, tool] of Object.entries(TOOLS)) {
    if (!enabledTools[key]) {
      log.info(`${tool.label}: skipped (disabled)`);
      continue;
    }

    const srcDir = path.join(PKG_ROOT, 'rules', tool.srcDir);
    const destDir = path.join(PROJECT_ROOT, tool.dest);

    if (!fs.existsSync(srcDir)) {
      log.warn(`${tool.label}: source not found (${srcDir}), skipping`);

      continue;
    }

    fs.mkdirSync(destDir, { recursive: true });

    for (const file of fs.readdirSync(srcDir)) {
      const destName = `${tool.filePrefix}${file}`;

      fs.copyFileSync(path.join(srcDir, file), path.join(destDir, destName));
      log.success(`${tool.label}: ${destName}`);
    }
  }
}

// ─── Dependency install ───────────────────────────────────────────────────────
async function ensureSavedDependency(): Promise<void> {
  const repoPkgPath = path.join(PROJECT_ROOT, 'package.json');

  if (!fs.existsSync(repoPkgPath)) {
    return;
  }

  let repoPkg: {
    devDependencies?: Record<string, string>;
    dependencies?: Record<string, string>;
  };

  try {
    repoPkg = JSON.parse(fs.readFileSync(repoPkgPath, 'utf8'));
  } catch {
    return;
  }

  const alreadySaved =
    repoPkg.devDependencies?.[pkg.name] ?? repoPkg.dependencies?.[pkg.name];

  if (alreadySaved) {
    return;
  }

  const save = await confirm({
    message: `Add ${pc.cyan(pkg.name)} to devDependencies?`,
    initialValue: true,
  });

  if (isCancel(save) || !save) {
    log.warn(`Skipped — run manually: npm install --save-dev ${pkg.name}`);

    return;
  }

  try {
    execSync(`npm install --save-dev ${pkg.name}`, {
      cwd: PROJECT_ROOT,
      stdio: 'inherit',
    });
    log.success(`${pkg.name} added to devDependencies`);
  } catch {
    log.warn(
      `npm install failed — add it manually: npm install --save-dev ${pkg.name}`,
    );
  }
}

// ─── Commands ─────────────────────────────────────────────────────────────────
async function cmdInit(options: Record<string, unknown>): Promise<void> {
  intro(pc.cyan('qa-ai-rules — init'));

  const toolSelection: Record<string, boolean> = {};

  const flaggedTools = Object.keys(TOOLS).filter((k) => options[k] === true);

  if (flaggedTools.length > 0) {
    for (const key of Object.keys(TOOLS)) {
      toolSelection[key] = options[key] === true;
    }

    log.info(`Tools from flags: ${JSON.stringify(toolSelection)}`);
  } else {
    const existing = loadConfig();

    if (existing) {
      log.warn(
        `Existing qa-ai-rules.config.json found: ${pc.dim(JSON.stringify(existing.tools))}`,
      );

      const reconfigure = await confirm({
        message: 'Reconfigure tool selection?',
        initialValue: false,
      });

      if (isCancel(reconfigure)) {
        cancel('Operation cancelled');
        process.exit(0);
      }

      if (!reconfigure) {
        log.info(
          'Keeping existing config — proceeding to .gitignore check and install',
        );

        await handleGitignore(existing.tools);
        installFiles(existing.tools);
        await ensureSavedDependency();
        outro(pc.green('Done!'));

        return;
      }
    }

    const selected = await multiselect({
      message: 'Select tools to enable:',
      options: Object.entries(TOOLS).map(([key, tool]) => ({
        value: key,
        label: tool.label,
        hint: tool.hint,
      })),
      required: false,
    });

    if (isCancel(selected)) {
      cancel('Operation cancelled');
      process.exit(0);
    }

    for (const key of Object.keys(TOOLS)) {
      toolSelection[key] = (selected as string[]).includes(key);
    }
  }

  const anyEnabled = Object.values(toolSelection).some(Boolean);

  if (!anyEnabled) {
    log.warn('No tools selected. Nothing to install.');
    outro('');

    return;
  }

  writeConfig(toolSelection);
  await handleGitignore(toolSelection);
  installFiles(toolSelection);
  await ensureSavedDependency();

  outro(
    pc.green(
      'All done! Commit qa-ai-rules.config.json and .gitignore. Generated rule files are gitignored.',
    ),
  );
}

async function cmdInstall(): Promise<void> {
  const config = loadConfig();

  if (!config) {
    log.info(
      'No qa-ai-rules.config.json found. Run `npx @metricinsights/qa-ai-rules` to set up.',
    );

    return;
  }

  intro(pc.cyan('qa-ai-rules — install'));
  log.info(`Config: ${JSON.stringify(config.tools)}`);
  installFiles(config.tools);
  outro('Install complete.');
}

function cmdStatus(): void {
  intro(pc.cyan('qa-ai-rules — status'));

  const config = loadConfig();

  if (!config) {
    log.warn(
      'No config found. Run `npx @metricinsights/qa-ai-rules` to get started.',
    );
    outro('');

    return;
  }

  const configLines = Object.entries(TOOLS)
    .map(([key, tool]) => {
      const enabled = config.tools?.[key] ?? false;

      return `${tool.label}: ${enabled ? pc.green('enabled') : pc.dim('disabled')}`;
    })
    .join('\n');

  log.info(`Config:\n${configLines}`);

  const fileLines: string[] = [];

  for (const [key, tool] of Object.entries(TOOLS)) {
    if (!config.tools?.[key]) {
      continue;
    }

    const destDir = path.join(PROJECT_ROOT, tool.dest);

    if (!fs.existsSync(destDir)) {
      fileLines.push(
        pc.yellow(`${tool.label}: destination directory missing (run install)`),
      );
      continue;
    }

    const files = fs
      .readdirSync(destDir)
      .filter((f: string) => !tool.filePrefix || f.startsWith(tool.filePrefix));

    if (files.length === 0) {
      fileLines.push(
        pc.yellow(`${tool.label}: no files found in ${tool.dest}`),
      );
    } else {
      files.forEach((f: string) =>
        fileLines.push(pc.green(`${tool.label}: ${path.join(tool.dest, f)}`)),
      );
    }
  }

  if (fileLines.length > 0) {
    log.info(`Installed files:\n${fileLines.join('\n')}`);
  }

  const { missing, stale } = getMissingIgnoreRules(config.tools);

  if (missing.length === 0 && stale.length === 0) {
    log.success('.gitignore: all rules in order');
  }

  missing.forEach((r) => log.warn(`.gitignore missing: ${r}`));
  stale.forEach((r) => log.warn(`.gitignore stale (disabled tool): ${r}`));

  outro('');
}

// ─── CLI setup ────────────────────────────────────────────────────────────────
const cli = cac('qa-ai-rules');

cli
  .command(
    'init',
    'Interactive setup: select tools, update .gitignore, install rules',
  )
  .option('--cursor', 'Enable Cursor IDE rules (skip prompt)')
  .option('--claude', 'Enable Claude Code rules (skip prompt)')
  .action(async (options: Record<string, unknown>) => {
    await cmdInit(options);
  });

cli
  .command(
    'install',
    'Install rules based on existing config (non-interactive, used by postinstall)',
  )
  .action(async () => {
    await cmdInstall();
  });

cli
  .command(
    'status',
    'Show current config, installed files, and .gitignore state',
  )
  .action(() => {
    cmdStatus();
  });

cli
  .command('', 'Interactive setup (default)')
  .action(async (options: Record<string, unknown>) => {
    await cmdInit(options);
  });

cli.help();
cli.version(pkg.version);

cli.on('command:*', () => {
  log.error(`Unknown command: ${cli.args.join(' ')}`);
  cli.outputHelp();
  
  process.exit(1);
});

cli.parse();
