name: Secret scan

# Shared gitleaks scan: https://github.com/mi-examples/mi-examples-workflows/blob/main/docs/workflows.md#secret-scanyml

on:
  pull_request:
    branches: [main, develop]

permissions: {}

concurrency:
  group: secret-scan-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  secret-scan:
    name: Secret scan
    permissions:
      contents: read
    uses: mi-examples/mi-examples-workflows/.github/workflows/secret-scan.yml@cf845c043bfdebca3b0db0df24cb8e0a6aa71dc6 # v0.5.0
