name: Secret scan

# Shared gitleaks scan: https://github.com/mi-examples/mi-examples-workflows/blob/main/docs/workflows.md#secret-scanyml

on:
  pull_request:
    branches: [main, develop]

permissions: {}

concurrency:
  group: secret-scan-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  secret-scan:
    name: Secret scan
    permissions:
      contents: read
    uses: mi-examples/mi-examples-workflows/.github/workflows/secret-scan.yml@36bd5b09ccf69bcaa68438cdd4f602a7628a6779 # v0.3.0
